### PR TITLE
Missing step to download components

### PR DESCRIPTION
**Pull request by aurelienduarte**

### CODE REVIEW

**Comment by Djimmer** [comment]
Thank you! Did you get it working? If you have any questions, feel free.

**Comment by aurelienduarte** [comment]
Pleasure...

**Comment by Djimmer** [comment]
Did you get it to work? I'm interested to start working on this project again. Could use some support ;-)

**Comment by aurelienduarte** [comment]
Hi - I'm currently at "To start OpenBTS" and waiting for my bladeRF to ship. Once it's here I can continue.

See the pull request on "Patch 2" many other touch-ups, I also did a little fix for the libcoredumper component keep an eye out for that.

**Pull request merged**
